services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamplatform
      PG_DATA: /data/postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  api-gateway:
    image: 'apigateway:latest'
    ports:
      - "8080:8080"
    container_name: api-gateway
    networks:
      - spring
    depends_on:
      - eureka
  user:
    image: 'userservice:latest'
    container_name: user
    environment:
      # - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/streamplatform
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - eureka
  stream:
    image: 'streamservice:latest'
    container_name: stream
    environment:
      # - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/streamplatform
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - eureka
  rtmp:
    image: 'nginx-rtmp-module:latest'
    entrypoint: ["nginx", "-g", "daemon off;"]
    ports:
      - "1935:1935"
      - "8086:8080"
    container_name: rtmp
    networks:
      - spring
    depends_on:
      - stream

  eureka:
    image: 'eureka-server:latest'
    ports:
      - "8761:8761"
      - "80:8080"
    container_name: eureka
    hostname: eureka
    networks:
      - spring
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: