server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: users
          uri: lb://user/
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: auth
          uri: lb://user/
          predicates:
          - Path=/api/v1/auth/**

        - id: streams
          uri: lb://stream
          predicates:
            - Path=/api/v1/streams/**
          filters:
            - AuthenticationFilter

        - id: events
          uri: lb://stream
          predicates:
            - Path=/api/v1/events/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true