server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user
          uri: lb://user/
          predicates:
            - Path=/api/v1/users/**
            - Path=/api/v1/auth/**
        - id: stream
          uri: lb://stream
          predicates:
            - Path=/api/v1/streams/**
            - Path=/api/v1/events/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
